// Homework #1 CS2263
//  Sina Khajeh pour
// Date: 9/13/21
//-----------------------------------------------------------------------------------------------------------------------
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;
import org.apache.commons.cli.*; //import apache

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    // add batch,help and output options to the set of options
    public static Options setOptions() {
        Options options = new Options();
        Option batch = Option.builder("b").longOpt("batch").argName("file").hasArg().desc("batch file containing expressions to evaluate").build();
        Option help = Option.builder("h").longOpt("help").argName("file").hasArg().desc("output file").build();
        Option output = Option.builder("o").longOpt("output").hasArg().desc("print usage message").build();
        options.addOption(batch);
        options.addOption(help);
        options.addOption(output);
        return options;
    }


    public static void main(String[] args) throws ParseException, IOException {
        Options options = setOptions(); //call set of options
        CommandLineParser parser = new DefaultParser(); //using command line order
        CommandLine cmd = parser.parse(options, args);
        if (cmd.hasOption("help")) { //help case
            System.out.println("usage: eval [OPTIONS]\n" + "Evaluation of simple mathematical expressions\n\n" + "-b,--batch <file>    batch file containing expressions to evaluate\n" + "-h,--help            print usage message\n" + "-o,--output <file>   output file\n" + "\n" + "Copyright (C) 2021 Sina Khajehpour");
            System.exit(0);
        } else if (cmd.hasOption("batch")) { //batch case
            String fileName = cmd.getOptionValue("batch");
            Path path = Paths.get(fileName);
            if (Files.exists(path)) {
                BufferedReader reader = Files.newBufferedReader(path);
                System.out.println(reader);
            } else { //help message in case that the path does not exist
                System.out.println("There is not any file with this name");
                System.out.println("usage: eval [OPTIONS]\n" + "Evaluation of simple mathematical expressions\n\n" + "-b,--batch <file>    batch file containing expressions to evaluate\n" + "-h,--help            print usage message\n" + "-o,--output <file>   output file\n" + "\n" + "Copyright (C) 2021 Sina Khajehpour");
                System.exit(1);

            }
        } else if (cmd.hasOption("output")) { //output case
            String fileName = cmd.getOptionValue("output");
            Path path = Paths.get(fileName);
            try {
                Files.deleteIfExists(path);
                Files.createFile(path);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
                System.exit(1);
            }
        }
    }




}

