// First Homework CS2263
//  Sina Khajeh pour
// Date: 9/13/21
//-----------------------------------------------------------------------------------------------------------------------
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import javax.swing.text.html.Option;
public class App{
    public static void main(String[] args) throws ParseException {
        Options options= new Options();
        options.addOption("h",false,"print usage message");
        options.addOption("b",false,"batch file containing expressions to evaluate");
        options.addOption("o",false,"output file");
        CommandLineParser parser=new DefaultParser();
        CommandLine cmd=parser.parse (options,args);
        if(cmd.hasOption("b") || cmd.hasOption("-batch")){
            System.out.println("Batch value: lib");
        }
        if(cmd.hasOption("o")|| cmd.hasOption("-output")){
            System.out.println("Output value: lib");
        }
        if(cmd.hasOption("h")|| cmd.hasOption("-help")){
           System.out.println("-b,--batch <file>    batch file containing expressions to evaluate\n" +
                   "-h,--help            print usage message\n" +
                   "-o,--output <file>   output file\n" +
                   "\n" +
                   "Copyright (C) 2021 Sina Khajehpour");
        }



























    }
}
